# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 10) do

  create_table "asset_types", :force => true do |t|
    t.column "name",         :string
    t.column "position",     :integer
    t.column "created_at",   :datetime,                :null => false
    t.column "updated_at",   :datetime,                :null => false
    t.column "lock_version", :integer,  :default => 0, :null => false
  end

  create_table "assets", :force => true do |t|
    t.column "entry_id",      :integer
    t.column "user_id",       :integer
    t.column "asset_type_id", :integer
    t.column "url",           :string
    t.column "description",   :text
    t.column "created_at",    :datetime,                :null => false
    t.column "updated_at",    :datetime,                :null => false
    t.column "lock_version",  :integer,  :default => 0, :null => false
  end

  add_index "assets", ["entry_id"], :name => "entry_id"
  add_index "assets", ["user_id"], :name => "user_id"

  create_table "attribute_values", :force => true do |t|
    t.column "name",         :string,   :default => "", :null => false
    t.column "created_at",   :datetime,                 :null => false
    t.column "updated_at",   :datetime,                 :null => false
    t.column "lock_version", :integer,  :default => 0,  :null => false
  end

  create_table "data_points", :force => true do |t|
    t.column "attribute_value_id", :integer
    t.column "entry_id",           :integer
    t.column "value",              :string,   :default => "", :null => false
    t.column "created_at",         :datetime,                 :null => false
    t.column "updated_at",         :datetime,                 :null => false
    t.column "lock_version",       :integer,  :default => 0,  :null => false
  end

  add_index "data_points", ["attribute_value_id"], :name => "attribute_value_id"
  add_index "data_points", ["entry_id"], :name => "entry_id"

  create_table "entries", :force => true do |t|
    t.column "organism_id",            :integer
    t.column "user_id",                :integer
    t.column "habitat_id",             :integer
    t.column "lat",                    :float,                         :null => false
    t.column "lon",                    :float,                         :null => false
    t.column "location",               :string,   :default => "",      :null => false
    t.column "date",                   :datetime
    t.column "description",            :text
    t.column "confidence_range",       :float,    :default => 0.0,     :null => false
    t.column "confidence_range_units", :string,   :default => "miles", :null => false
    t.column "created_at",             :datetime,                      :null => false
    t.column "updated_at",             :datetime,                      :null => false
    t.column "lock_version",           :integer,  :default => 0,       :null => false
  end

  add_index "entries", ["organism_id"], :name => "organism_id"
  add_index "entries", ["user_id"], :name => "user_id"

  create_table "habitats", :force => true do |t|
    t.column "name",         :string
    t.column "position",     :integer
    t.column "created_at",   :datetime,                :null => false
    t.column "updated_at",   :datetime,                :null => false
    t.column "lock_version", :integer,  :default => 0, :null => false
  end

  create_table "images", :force => true do |t|
    t.column "entry_id",     :integer
    t.column "user_id",      :integer
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "created_at",   :datetime,                :null => false
    t.column "updated_at",   :datetime,                :null => false
    t.column "lock_version", :integer,  :default => 0, :null => false
  end

  add_index "images", ["entry_id"], :name => "entry_id"
  add_index "images", ["user_id"], :name => "user_id"

  create_table "organism_infos", :force => true do |t|
    t.column "organism_id",  :integer
    t.column "user_id",      :integer
    t.column "date",         :datetime
    t.column "description",  :text
    t.column "created_at",   :datetime,                :null => false
    t.column "updated_at",   :datetime,                :null => false
    t.column "lock_version", :integer,  :default => 0, :null => false
  end

  add_index "organism_infos", ["user_id"], :name => "user_id"
  add_index "organism_infos", ["organism_id"], :name => "organism_id"

  create_table "organisms", :force => true do |t|
    t.column "block_id",     :integer
    t.column "child_id",     :integer
    t.column "union_id",     :integer
    t.column "name",         :string,   :default => "", :null => false
    t.column "created_at",   :datetime,                 :null => false
    t.column "updated_at",   :datetime,                 :null => false
    t.column "lock_version", :integer,  :default => 0,  :null => false
  end

  create_table "users", :force => true do |t|
    t.column "password_salt", :string
    t.column "password_hash", :string
    t.column "email",         :string,   :default => "",    :null => false
    t.column "fullname",      :string,   :default => "",    :null => false
    t.column "institution",   :string,   :default => ""
    t.column "address",       :text
    t.column "active",        :boolean,  :default => true,  :null => false
    t.column "admin",         :boolean,  :default => false, :null => false
    t.column "created_at",    :datetime,                    :null => false
    t.column "updated_at",    :datetime,                    :null => false
    t.column "lock_version",  :integer,  :default => 0,     :null => false
  end

end
